### PR TITLE
feat: deflate64 decompression support 

### LINKED ISSUE #100: deflate64 support
Windows may creates zip file with deflate64 compression method but this library doesn't support deflate64 so decompressing such zip file.
I want to decompress such a zip file so I want rs-async-zip to support deflate64.

Depends on Nullus157/async-compression#237

### PR DESCRIPTION
**Pull request by anatawa12**
Closes #100

Depends on Nullus157/async-compression#238

### CODE REVIEW

**Comment by anatawa12** [comment]
Pull Request in async-compression has been merged so this pull request is ready for review.

**Comment by anatawa12** [comment]
Sorry again. I've fixed formatting.

**Comment by anatawa12** [comment]
I'm so sorry again. I forgot to test only with "deflate64" feature

**Comment by Majored** [comment]
Thanks for the work - merging 👍

**Pull request merged**
